# Site description
title: tok09
name: tok09
description: >- 
  tok09 is x .
site.locale: "cn-GB"
# site.locale: "GB-GB"

# URLs and permalinks
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tok09.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "tok09.github.io"

# Author information
author:
  name: "tok09"
  avatar: "/images/avatar.png"
  bio: |
    亚史.

    [&larr;](https://tok09.github.io)
    *[ARCHAEORING](https://tok09.github.io)*
    [&rarr;](https://tok09.github.io)
  location: "Denmark"
  links:
    - label: "tok09.github.io"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:tok09.github.io"
    - label: "0000-0002-1011-1244"
      icon: "ai ai-fw ai-orcid"
      url: "https://tok09.github.io"
    - label: "Google Scholar"
      icon: "ai ai-fw ai-google-scholar"
      url: "https://tok09.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://tok09.github.io"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://tok09.github.io"
    - label: "Wikipedia"
      icon: "fab fa-fw fa-wikipedia-w"
      url: "https://tok09.github.io"
 
# Social media
twitter:
  username: "tok09"

# Content types
collections:
  code:
    output: true
  datasets:
    output: true
  papers:
    output: true
  papers:
    output: true
  posters:
    output: true
  talks:
    output: true
  blog:
    output: true

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      share: true
      related: true
  - scope:
      path: ""
      type: "code"
    values:
      layout: "program"
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: "dataset"
  - scope:
      path: ""
      type: "papers"
    values:
      layout: "paper"
  - scope:
      path: ""
      type: "posters"
    values:
      layout: "poster"
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "talk"

# Breadcrumbs
breadcrumbs: false

# Excerpts
excerpt_separator: <!-- more -->

# Home page pagination
# paginate: 5
# paginate_path: /page:num/

# Taxonomy
tag_archive:
  type: liquid
  path: /tags/

# Feed
feed:
  tags: 
    only:
      - R
    path: /feed/

# Build settings
markdown: kramdown
include:
  - _pages
exclude:
  - "*.Rmd"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from
